// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcuwxjvcwuzeomzgqtbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdXd4anZjd3V6ZW9temdxdGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTUyOTIsImV4cCI6MjA2OTI3MTI5Mn0.J1HCPXcx3dJHzamK7WhfOQS-P9_QIXNdu2IPEIjae1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});